### ISSUE TITLE
Answer correctness not working

### ISSUE THREAD

**Issue by ekaanshkhosla** [explodinggradients/ragas#1774]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
Answer correctness not working

Ragas version:
Python version:

**Code to Reproduce**
```
from datasets import Dataset 
from ragas.metrics import faithfulness, answer_correctness
from ragas import evaluate

data_samples = {
    'question': ['What is France capital?', 'What is India capital?'],
    'answer': ['France capital is Delhi', 'India capital is spain'],
    'ground_truth': ['France capital is Paris.', 'India capital is Delhi']
}
dataset = Dataset.from_dict(data_samples)
score = evaluate(dataset,metrics=[answer_correctness])
score.to_pandas()
```
**Error trace**

**Expected behavior**

**Additional context**

**Comment by hundredeuk2** [comment]
You didn't specify the error type, Python version, or RAGAS version, so I can't tell what it is, but if it's a "metaclass conflict" problem, it should be fixed by upgrading the langchain library.

Error Type in VertexAI
`TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

Solve
`pip install --upgrade ragas langchain`

**Comment by jjmachan** [comment]
thanks a lot of the helping out @hundredeuk2 🙌🏽 

@ekaanshkhosla were you able to solve it? could you share the error trace if it was not solved?
