### ISSUE TITLE
Merge node error for multi_context evolutions

### ISSUE THREAD

**Issue by srikanthmalla** [explodinggradients/ragas#647]
**Describe the bug**
Runner in Executor raised an exception
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ragas/lib/python3.10/site-packages/ragas/executor.py", line 58, in _aresults
    r = await future
  File "/home/user/anaconda3/envs/ragas/lib/python3.10/asyncio/tasks.py", line 575, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/user/anaconda3/envs/ragas/lib/python3.10/site-packages/ragas/executor.py", line 91, in wrapped_callable_async
    return counter, await callable(*args, **kwargs)
  File "/home/user/anaconda3/envs/ragas/lib/python3.10/site-packages/ragas/testset/evolutions.py", line 163, in evolve
    return await self.generate_datarow(
  File "/home/user/anaconda3/envs/ragas/lib/python3.10/site-packages/ragas/testset/evolutions.py", line 210, in generate_datarow
    merged_nodes = self.merge_nodes(relevant_context)
  File "/home/user/anaconda3/envs/ragas/lib/python3.10/site-packages/ragas/testset/evolutions.py", line 75, in merge_nodes
    embed_dim = len(nodes.nodes[0].embedding) if nodes.nodes[0].embedding else None
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Ragas version: 0.1.1
Python version: 3.10.0

This only happens for `multi_context` evolutions.

**Comment by daveyko** [comment]
also getting the same error

**Comment by shahules786** [comment]
Hey @srikanthmalla @daveyko I have fixed this issue, please install ragas from source :) Will make a release soon

**Comment by AnnaKelmanson** [comment]
> Hey @srikanthmalla @daveyko I have fixed this issue, please install ragas from source :) Will make a release soon Sorry for the trouble guys

Hi! I tried one more time with the source. It does not raise an error, but it still doesn't produce multi-context questions.

**Comment by shahules786** [comment]
Hey @AnnaKelmanson Can you share the code you used? And make sure that the distribution you used has multi_context in it?

**Comment by shahules786** [comment]
This particular error has been fixed #617 , so closing the issue. Feel free reopen if required.

**Comment by AnnaKelmanson** [comment]
> Hey @AnnaKelmanson Can you share the code you used? And make sure that the distribution you used has multi_context in it? 

I used the code from the documentation examples for test set generation.
